# Generated by Django 3.0.5 on 2020-04-29 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nameoflist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameoflist', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicname', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ListSorting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(0)])),
                ('listname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quize.Nameoflist')),
            ],
        ),
        migrations.CreateModel(
            name='Blank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank', models.CharField(max_length=150)),
                ('blankanswer', models.CharField(max_length=150)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quize.Topic')),
            ],
        ),
    ]
